pipeline {
  agent any

  tools {
    jdk 'JAVA_HOME'
    maven 'M2_HOME'
  }

  stages {
    stage('Checkout') {
      steps {
        echo "Checkout handled by Jenkins (Pipeline script from SCM)"
      }
    }

    stage('Compile Stage') {
      steps {
        dir('student-management') {
          sh 'mvn -v'
          sh 'mvn clean compile'
        }
      }
    }
  }
}
